<?php
/**
 * Created by IntelliJ IDEA.
 * User: mohammad
 * Date: 8/6/15
 * Time: 12:16 PM
 */

namespace QUIZUP\Libraries\Exceptions;

class Exception extends \Exception{
    public function __construct($message = "", $code = 0, \Exception $previous = null)
    {
        \Exception::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }


}